### ISSUE TITLE
Host field only works with IP addresses

### ISSUE THREAD

**Issue by michaelpiron** [la7dja/esphome-influxdb#1]
Hi,

i have successfully been using this component to send measured data of my energy plug (Blitzwolf SHP6 running ESPhome) to my influxdb 1.8 database.

This is my configuration:
```
# Connection to InfluxDB
influxdb:
  host: 192.168.84.16
  port: 8089
  publish_all: false
  tags:
    device: '${device_name}'
    client: '${client_name}'
    sensor: '${sensor_name}'
  sensors:
    power:
      ignore: false
      measurement: 'plugs'
      tags:
        units: 'Watts'
    voltage:
      ignore: false
      measurement: 'plugs'
      tags:
        units: 'Volts'
```

This worked as long as I specified an IP address in the "host" section. (either the local LAN IP address of my Influxdb host, either my public IP address)
However, when I replace the IP address by a domain ( subdomain.domain.be or myname.synology.me), the data doesn't arrive in my Influxdb anymore. The ESPHome log doesn't give any error message, so the specified domain seems to be valid.

I tried different ways of entering the domain:
`host: subdomain.domain.be`
or
`host: "subdomain.domain.be"`
or
`host: 'subdomain.domain.be'`

They all give the same result: no error messages in ESPHome log, but no data arrives in my influxDB.
